# Generated by Django 4.0.4 on 2022-05-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruits and vegetables', 'Fruits Vegetables'), ('meat', 'Meat'), ('diary', 'Diary'), ('dry good', 'Dry Goods'), ('alcohols', 'Alcohols'), ('medicine', 'Medicine'), ('pet goods', 'Pet Goods'), ('baby goods', 'Baby Goods'), ('domestic detergents', 'Domestic Detergents'), ('ready-cook meals', 'Ready Cook Meals'), ('hygiene', 'Hygiene'), ('coffee & tea', 'Coffee Tea'), ('frozen foods', 'Frozen Foods'), ('garden and tinkering', 'Garden Tinker'), ('bread', 'Bread'), ('preserves', 'Preserves'), ('spices, sauces, additives', 'Spices'), ('fishes and seafood', 'Fish'), ('sweets and snacks', 'Sweets'), ('fats', 'Fats'), ('water and drinks', 'Drinks'), ('dried fruit and nuts', 'Nuts'), ('fresh herbs', 'Herbs'), ('canned food', 'Cans'), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('pkgs', 'Packages'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
