# Generated by Django 4.0.4 on 2022-05-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_item_shopping_list_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
