# Generated by Django 4.0.4 on 2022-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
