# Generated by Django 4.0.4 on 2022-05-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_item_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['active']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='complete',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='timestamp',
            new_name='created',
        ),
    ]
